"""Nightly learning loop and model registry."""

from trading_app.learning.arena import (
    ModelArena,
    ModelArenaSnapshot,
    ModelComparisonResult,
    ModelEvidenceRecord,
    ModelEvidenceType,
    ModelMetricSet,
    ModelPostmortem,
    ModelPromotionRequest,
    PromotionApproval,
)
from trading_app.learning.models import (
    CandidateEvaluation,
    CandidateSpec,
    CandidateTrainingRecord,
    ChampionChallengerComparison,
    FeatureObservation,
    FeatureUpdateRecord,
    ModelRegistrySnapshot,
    ModelRegistryState,
    ModelVersionRecord,
    NightlyLearningConfig,
    NightlyLearningRun,
    PromotionAction,
    PromotionRecommendation,
    WalkForwardFold,
    WalkForwardFoldResult,
    WalkForwardMetrics,
)
from trading_app.learning.nightly import (
    CandidateModelTrainer,
    FeatureUpdater,
    NightlyLearningLoop,
    WalkForwardEvaluator,
    build_walk_forward_folds,
    render_learning_markdown_report,
    write_learning_markdown_report,
)
from trading_app.learning.registry import ModelRegistry, ModelRegistryError

__all__ = [
    "CandidateEvaluation",
    "CandidateModelTrainer",
    "CandidateSpec",
    "CandidateTrainingRecord",
    "ChampionChallengerComparison",
    "FeatureObservation",
    "FeatureUpdateRecord",
    "FeatureUpdater",
    "ModelArena",
    "ModelArenaSnapshot",
    "ModelComparisonResult",
    "ModelEvidenceRecord",
    "ModelEvidenceType",
    "ModelMetricSet",
    "ModelPostmortem",
    "ModelPromotionRequest",
    "ModelRegistry",
    "ModelRegistryError",
    "ModelRegistrySnapshot",
    "ModelRegistryState",
    "ModelVersionRecord",
    "NightlyLearningConfig",
    "NightlyLearningLoop",
    "NightlyLearningRun",
    "PromotionAction",
    "PromotionApproval",
    "PromotionRecommendation",
    "WalkForwardEvaluator",
    "WalkForwardFold",
    "WalkForwardFoldResult",
    "WalkForwardMetrics",
    "build_walk_forward_folds",
    "render_learning_markdown_report",
    "write_learning_markdown_report",
]
